name: docs

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  deploy:
    name: Build and deploy documentation
    if: ${{ vars.CLOUDFLARE_WORKER_NAME != '' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    environment:
      name: website
      url: https://mashumaro.io/

    steps:
      - name: Checkout release
        uses: actions/checkout@v7

      - name: Set up Python 3.14
        uses: actions/setup-python@v7
        with:
          python-version: "3.14"

      - name: Build documentation
        run: python web/build.py

      - name: Deploy to Cloudflare Workers
        uses: cloudflare/wrangler-action@v4
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: deploy --name=${{ vars.CLOUDFLARE_WORKER_NAME }} --assets=web/dist --compatibility-date=2026-09-16
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
